name: CI

on:
  push:
    branches: [ "parser-release" ]
  pull_request:
    branches: [ "parser-release" ]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.2"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        run: poetry install

      - name: install pyinstaller
        run: poetry run pip install -U pyinstaller
      - name: Build execution file
        run: poetry run pyinstaller main.py --onefile

      - uses: actions/setup-node@v3
        with: 
          node-version: '16'
      
      - name: rename built binary
        run: poetry run mv ./dist/main ./dist/main-${{ matrix.os }}

      - name: Store built binary
        uses: actions/upload-artifact@v2
        with:
          name: parser-binary
          path: ./dist
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'

      - name: Download built binary
        uses: actions/download-artifact@v2
        with:
          name: parser-binary
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          name: parser-binary
          tag_name: release
    permissions:
      contents: write

# upload artifact instead, new job between for release once artifacts uploaded
# use som downloadartifact command 