name: Code Style
on: [push]

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: set npm version
        run: npm install -g npm@8.3.1
      - name: Install npm dependencies
        run: npm ci
      - name: Eslint
        run: npm run eslint:ci
#      - name: Stylelint
#        run: npm run lint:css
# styelelint is not working correctly
